### PR TITLE
changes as dstk is down

### PR DESCRIPTION
**Pull request by andrewqchong**

### CODE REVIEW

**Comment by andrewqchong** [comment]
merged

**Comment by deniederhut** [comment]
@andrewqchong do you not have authorization to merge pull requests on this repo?

**Comment by pattyf** [comment]
I don't want Andrew to change Juan's course - but to have a different
branch or repo since his is fundamentally different (not dstk).

thanks,
p

On Wed, Sep 23, 2015 at 2:55 PM, Dillon Niederhut notifications@github.com
wrote:

> @andrewqchong https://github.com/andrewqchong do you not have
> authorization to merge pull requests on this repo?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dlab-berkeley/geocoding-workshop/pull/2#issuecomment-142742240
> .

## 

Patty Frontiera
Academic Coordinator
D-Lab, _Supporting Data Intensive Social Science for All_
356 Barrows Hall, University of California Berkeley
http://dlab.berkeley.edu

**Comment by andrewqchong** [comment]
Sure, I'll create a separate repo. I spoke to Dav and he made me a owner.

**Pull request closed without merging**
